{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/init()"},"sections":[],"metadata":{"role":"symbol","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"iNaviNavigationSdk"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@iNaviNavigationSdk@objc(cs)InaviController(im)init","title":"init()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/init()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"]]},"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/init()":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/init()","title":"init()","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/init()","type":"topic","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","url":"\/documentation\/inavinavigationsdk\/inavicontroller","type":"topic","title":"InaviController","navigatorTitle":[{"text":"InaviController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InaviController","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","type":"topic","title":"iNaviNavigationSdk","url":"\/documentation\/inavinavigationsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1init()\/title","op":"replace","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title","value":"InaviController"},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments","value":[{"kind":"identifier","text":"InaviController"}]},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle","value":[{"text":"InaviController","kind":"identifier"}]}]}]}