{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"iNaviNavigationSdk"}],"externalID":"s:18iNaviNavigationSdk15InaviControllerC18setMapModeListener8listeneryyAA0gH6StatusOc_tF","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapModeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MapModeStatus","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk13MapModeStatusO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"setMapModeListener(listener:)"},"sections":[],"abstract":[{"text":"Sets the map mode listener.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/setmapmodelistener(listener:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapModeListener(listener:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapModeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:18iNaviNavigationSdk13MapModeStatusO","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/MapModeStatus","text":"MapModeStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The listener for map mode changes."}]}],"name":"listener"}],"kind":"parameters"}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","type":"topic","title":"iNaviNavigationSdk","url":"\/documentation\/inavinavigationsdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapModeListener(listener:)":{"type":"topic","abstract":[{"text":"Sets the map mode listener.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapModeListener(listener:)","title":"setMapModeListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapModeListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"MapModeStatus","preciseIdentifier":"s:18iNaviNavigationSdk13MapModeStatusO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapmodelistener(listener:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/MapModeStatus":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/MapModeStatus","title":"MapModeStatus","url":"\/documentation\/inavinavigationsdk\/mapmodestatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MapModeStatus","kind":"identifier"}],"navigatorTitle":[{"text":"MapModeStatus","kind":"identifier"}],"type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","url":"\/documentation\/inavinavigationsdk\/inavicontroller","type":"topic","title":"InaviController","navigatorTitle":[{"text":"InaviController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InaviController","kind":"identifier"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"InaviController","op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title"},{"value":[{"kind":"identifier","text":"InaviController"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments"},{"value":[{"text":"InaviController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}