{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSCoding","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSObject","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CALayerDelegate","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s7CVarArgP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s28CustomDebugStringConvertibleP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s23CustomStringConvertibleP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SQ","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SH","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s8SendableP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s16SendableMetatypeP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearance","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearanceContainer","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIDynamicItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusEnvironment","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItemContainer","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UITraitEnvironment","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIUserActivityRestoring","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UICoordinateSpace"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvSimpleSearchBar","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSimpleSearchBar","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/invsimplesearchbar"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/invsimplesearchbar"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"InvSimpleSearchBar"}],"role":"symbol","externalID":"c:@M@iNaviNavigationSdk@objc(cs)InvSimpleSearchBar","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvSimpleSearchBar"}],"title":"InvSimpleSearchBar","modules":[{"name":"iNaviNavigationSdk"}],"symbolKind":"class"},"sections":[],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIUserActivityRestoring"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"type":"topic","title":"iNaviNavigationSdk","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/inavinavigationsdk","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItemContainer"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearance","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s16SendableMetatypeP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)UIView"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SQ","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s7CVarArgP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UICoordinateSpace":{"title":"UIUtilities.UICoordinateSpace","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s23CustomStringConvertibleP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SH"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIResponderStandardEditActions"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusEnvironment"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItem"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s8SendableP","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/5UIKit23UITraitChangeObservableP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSimpleSearchBar":{"kind":"symbol","url":"\/documentation\/inavinavigationsdk\/invsimplesearchbar","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSimpleSearchBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvSimpleSearchBar"}],"title":"InvSimpleSearchBar","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvSimpleSearchBar"}],"type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSCoding","title":"Foundation.NSCoding"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"InvSimpleSearchBar","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InvSimpleSearchBar"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"InvSimpleSearchBar","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)UIView"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvSimpleSearchBar","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvSimpleSearchBar\/title","value":"InvSimpleSearchBar","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvSimpleSearchBar\/fragments","value":[{"text":"InvSimpleSearchBar","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvSimpleSearchBar\/navigatorTitle","value":[{"kind":"identifier","text":"InvSimpleSearchBar"}],"op":"replace"}]}]}