{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionDidChangeWith:animated:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"MLNMapViewDelegate.mapView(_:regionDidChangeWith:animated:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regiondidchangewith:animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regiondidchangewith:animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"metadata":{"modules":[{"name":"iNaviNavigationSdk"}],"role":"symbol","extendedModule":"iNaviNavigationSdk","title":"mapView(_:regionDidChangeWith:animated:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"mapView:regionDidChangeWithReason:animated:"}],"roleHeading":"Instance Method","externalID":"c:@CM@iNaviNavigationSdk@objc(cs)InvMapView(im)mapView:regionDidChangeWithReason:animated:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView"},{"text":", ","kind":"text"},{"text":"regionDidChangeWith","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLNCameraChangeReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@MLNCameraChangeReason"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mapView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"regionDidChangeWith","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MLNCameraChangeReason","preciseIdentifier":"c:@E@MLNCameraChangeReason","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"type":"topic","title":"iNaviNavigationSdk","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/inavinavigationsdk","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapView(_:regionDidChangeWith:animated:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionDidChangeWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@MLNCameraChangeReason","text":"MLNCameraChangeReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regiondidchangewith:animated:)","navigatorTitle":[{"kind":"identifier","text":"mapView:regionDidChangeWithReason:animated:"}],"abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionDidChangeWith:animated:)","title":"mapView(_:regionDidChangeWith:animated:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvMapView"}],"title":"InvMapView","url":"\/documentation\/inavinavigationsdk\/invmapview","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvMapView"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"mapView:regionDidChangeWithReason:animated:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mapView:regionDidChangeWithReason:animated:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"mapView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView"},{"text":" *) ","kind":"text"},{"text":"mapView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"regionDidChangeWithReason:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNCameraChangeReason","preciseIdentifier":"c:@E@MLNCameraChangeReason","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"animated:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionDidChangeWith:animated:)\/title","value":"mapView:regionDidChangeWithReason:animated:"},{"value":[{"text":"- ","kind":"text"},{"text":"mapView:regionDidChangeWithReason:animated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionDidChangeWith:animated:)\/fragments"},{"value":"InvMapView","op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title"},{"value":[{"text":"InvMapView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments"},{"value":[{"kind":"identifier","text":"InvMapView"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle"}]}]}