{"sections":[],"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@iNaviNavigationSdk@objc(cs)InvMapView","title":"InvMapView","navigatorTitle":[{"kind":"identifier","text":"InvMapView"}],"roleHeading":"Class","modules":[{"name":"iNaviNavigationSdk"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvMapView"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/inavinavigationsdk\/invmapview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/inavinavigationsdk\/invmapview"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSCoding","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)MLNMapViewDelegate","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSObject","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CALayerDelegate","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s7CVarArgP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s8CopyableP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s28CustomDebugStringConvertibleP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s23CustomStringConvertibleP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SQ","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SH","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s8SendableP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s16SendableMetatypeP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAccessibilityIdentification","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearance","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearanceContainer","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIDynamicItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusEnvironment","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItemContainer","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UILargeContentViewerItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIResponderStandardEditActions","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/5UIKit23UITraitChangeObservableP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UITraitEnvironment","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIUserActivityRestoring","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UICoordinateSpace"],"kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/MLNMapViewDelegate-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItemContainer"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s7CVarArgP":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SH"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIDynamicItem"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UITraitEnvironment"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s8CopyableP":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s28CustomDebugStringConvertibleP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SQ"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s8SendableP":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPasteConfigurationSupporting"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIUtilities.UICoordinateSpace"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","abstract":[],"navigatorTitle":[{"text":"InvMapView","kind":"identifier"}],"title":"InvMapView","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invmapview"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearanceContainer"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIFocusItem"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(cs)UIView":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s23CustomStringConvertibleP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s16SendableMetatypeP":{"type":"unresolvable","title":"Swift.SendableMetatype","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s16SendableMetatypeP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","type":"topic","title":"iNaviNavigationSdk","url":"\/documentation\/inavinavigationsdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)MLNMapViewDelegate":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)MLNMapViewDelegate","type":"unresolvable","title":"MLNMapViewDelegate"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSObject"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)NSCoding":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/5UIKit23UITraitChangeObservableP"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)UIAppearance"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/MLNMapViewDelegate-Implementations":{"type":"topic","abstract":[],"title":"MLNMapViewDelegate Implementations","url":"\/documentation\/inavinavigationsdk\/invmapview\/mlnmapviewdelegate-implementations","kind":"article","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/MLNMapViewDelegate-Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"InvMapView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"InvMapView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"InvMapView"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Default Implementations","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/MLNMapViewDelegate-Implementations"],"generated":true,"anchor":"Default-Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)UIView"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)MLNMapViewDelegate"],"type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvMapView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","value":"InvMapView"},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","value":[{"text":"InvMapView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","value":[{"text":"InvMapView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}