{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NaviSDKVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"NaviSDKVersionString","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NaviSDKVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"navigatorTitle":[{"text":"NaviSDKVersionString","kind":"identifier"}],"roleHeading":"Global Variable","modules":[{"name":"iNaviNavigationSdk"}],"externalID":"c:@NaviSDKVersionString","role":"symbol","symbolKind":"var"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk"]]},"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionString","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/navisdkversionstring"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/navisdkversionstring"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Project version string for NaviSDK."}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","type":"topic","title":"iNaviNavigationSdk","url":"\/documentation\/inavinavigationsdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/NaviSDKVersionString":{"role":"symbol","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionString","url":"\/documentation\/inavinavigationsdk\/navisdkversionstring","title":"NaviSDKVersionString","abstract":[{"type":"text","text":"Project version string for NaviSDK."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NaviSDKVersionString"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"NaviSDKVersionString"},{"kind":"text","text":": <<error type>>"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"NaviSDKVersionString","op":"replace"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NaviSDKVersionString"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned char","kind":"typeIdentifier","preciseIdentifier":"c:c"},{"text":" ","kind":"text"},{"text":"NaviSDKVersionString","kind":"identifier"},{"text":"[];","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1NaviSDKVersionString\/title","value":"NaviSDKVersionString","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1NaviSDKVersionString\/fragments","value":[{"text":"NaviSDKVersionString","kind":"identifier"}],"op":"replace"}]}]}